// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PineriverData;

namespace PineriverData.Migrations
{
    [DbContext(typeof(PineriverContext))]
    [Migration("20190409175146_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PineriverData.Entities.Post", b =>
                {
                    b.Property<int>("Post_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Post_Created");

                    b.Property<int>("Post_Downvotes");

                    b.Property<string>("Post_Message");

                    b.Property<string>("Post_Subject");

                    b.Property<int>("Post_Upvotes");

                    b.Property<string>("User_ID");

                    b.HasKey("Post_ID");

                    b.ToTable("posts");
                });
#pragma warning restore 612, 618
        }
    }
}
